### ISSUE TITLE
Bugs on Nick's end [10/23/17]

### ISSUE THREAD

**Issue by mthuc** [manotoor/IBM_Watson#1]
Running on Eclipse on Windows 10 Home N

Bugs on my end:
[x] classify images not importing / loading properly (however, the package is visible in my dependencies)
[ ] classifying images not working, got import working

See: https://github.com/manotoor/IBM_Watson/blob/master/BugsAndSuggestions.txt

**Comment by manotoor** [comment]
You have to update to the latest git version.  The old ibm watson stopped
working so I updated it to the latest version 4.0.0
Also keep checking discord guys

**Comment by mthuc** [comment]
Checking again when I'm out of class. The version I pulled from was the last one you pushed out.

**Comment by manotoor** [comment]
Okay thank you,  I'll double check it. I might not have pushed the pom.xml
file

**Comment by mthuc** [comment]
Yeah, check again, but I have 4.0.0 as the one, but "choosing" is still freezing. Just a heads up (both on MacOS and Windows)

**Comment by manotoor** [comment]
Yo I'm in the computer lab, my phone's dead. I don't see you

**Comment by manotoor** [comment]
Yo I’m in the computer lab, my phone died

Sent from Mail for Windows 10
